### PR TITLE
Remove uncommon aliases

### PR DESCRIPTION
**Pull request by gylaz**

### CODE REVIEW

**Comment by tute** [comment]
I use only one of those. I'm ok with moving it to my custom dotfile.

**Comment by mcmire** [comment]
I've never used any of the ones you removed or variations thereof, so this makes sense to me.

**Comment by croaky** [comment]
I use `m` and `s` but not the others.

**Comment by jessieay** [comment]
I don't use any of these. Always feel like I should study / use the dotfile aliases more, but perhaps the fact that I've gone this long without using them means I don't need them at all...

**Comment by andyw8** [comment]
I use `rk` and `s` almost every day,

**Comment by mike-burns** [comment]
The `ln` one simply improves the output of ln(1), making it more clear what it just did - handy because the order of the arguments are confusing to some. That seems like something that should stay, unless we expect people to use ln(1) so often that they feel comfortable with it.

**Comment by geoffharcourt** [comment]
I used to use the `rk` alias often, but I found there were enough scenarios where I had to run it with `bundle exec` that I gave up on it.

**Comment by JoelQ** [comment]
I don't use any of these

**Comment by derekprior** [comment]
I use some of these. I don't mind moving them to my own aliases, but I don't understand the line drawn here. To me there are a couple of different types of aliases define here:

**Shortcuts:**

* `b`
* `rk`
* `tlf*
* `e`
* `v`
* ...

** Best Practice/Common Error Avoidance:

* `ln`
* `mkdir`
* `migrate`
* `path`

I think everything in the latter category is worth keeping, but am not sure how we draw the line on the first category. I'd consider axing the entire first category.

**Comment by jferris** [comment]
> I think everything in the latter category is worth keeping, but am not sure how we draw the line on the first category. I'd consider axing the entire first category.

I feel the same way about this.

**Comment by gylaz** [comment]
> am not sure how we draw the line

My intention for this PR is to tease out that line.

I agree that best practices should stay.

**Comment by MattMSumner** [comment]
I don't use any of these. :+1:

**Pull request merged**
