### PR TITLE
Enable autocomplete with dictionary words

### PR DESCRIPTION
**Pull request by andyw8**
Enable autocomplete with dictionary words when spell check is on

@georgebrock [demonstrated this](https://vimeo.com/122615319) at the Vim London Meetup yesterday. Seems like a useful thing to pull into the thoughtbot dotfiles?

### CODE REVIEW

**Comment by dideler** [comment]
How do you use this autocomplete? E.g. <kbd>CTRL</kbd>+<kbd>SPACE</kbd> or <kbd>CTRL</kbd>+<kbd>X</kbd> then some other combination?

**Comment by andyw8** [comment]
CTRL-X then 's'.

**Comment by jferris** [comment]
This seems cool to me. @gylaz?

**Comment by gylaz** [comment]
Yep! Merged as fc4f0118620162eba287fe5b435d858603af1920.

**Pull request closed without merging**
