### PR TITLE
Add `git branches` command

### PR DESCRIPTION
**Pull request by iwz**
* Lists all remote branches
* Sorts by last commit date, descending
* Shows how long the branch has been around
* Shows last commit author

```
$ git branches
6 days ago  Dan Croak  origin/HEAD
6 days ago  Dan Croak  origin/master
5 months ago  Dan Croak  origin/dc-rbenv-zsh
6 months ago  Sean Doyle  origin/sd-nvm-path
6 months ago  Tute Costa  origin/vim-multiple-cursors
7 months ago  Sean Doyle  origin/sd-vundle
8 months ago  Sean Griffin  origin/sg-disable-spring
9 months ago  Mike Burns  origin/mb-experimental-tag
```

git branches command

### CODE REVIEW

**Comment by tabfugnic** [comment]
Hmm, I feel like `dc-psql-x-auto` should probably be deleted

**Comment by tabfugnic** [comment]
LGTM

**Comment by tute** [comment]
ha! I just deleted my stale branch. I used to use `gold`:

`alias gold='git branch -a | grep origin | grep -v HEAD | xargs -n 1 git log --date=iso --pretty=format:"%an %ad %d%n" -1 --decorate | grep -v master | sort'`

**Comment by iwz** [comment]
@tabfugnic mind testing this on unix?

**Comment by tute** [comment]
```
suspenders master % gold
Caleb Thompson 2015-01-26 20:03:07 -0600  (origin/ct-dont-give-a-damn)
Caleb Thompson 2015-02-02 16:08:06 -0600  (origin/ct-unicorn)
Damian Galarza 2015-02-19 14:21:54 -0500  (origin/require-spec-helper)
Dan Croak 2015-01-27 18:05:52 -0800  (origin/dc-user-facing-flashes)
Dan Croak 2015-01-27 18:45:55 -0800  (origin/dc-staging)
Geoff Harcourt 2013-03-18 11:57:03 -0400  (origin/dc-disable-unused-generators)
Jessie A. Young 2014-07-11 15:33:00 -0700  (origin/jy-remove-comments)
Mike Burns 2014-11-24 19:12:04 +0100  (origin/command)
Mike Burns 2015-02-04 16:36:24 +0100  (origin/opt-in)
Tute Costa 2015-02-20 13:21:05 -0500  (origin/tc-simplecov, tc-simplecov)
```

**Comment by mcmire** [comment]
Oooh, purty... :+1:

**Comment by mike-burns** [comment]
I dig it.

Locally, I changed mine to this:

    branches = for-each-ref --sort=-committerdate --format=\"%(authordate:short)\t%(authorname)\t%(refname:short)\" refs/remotes

But yours is indeed prettier.

**Comment by gylaz** [comment]
Looks good to me.

**Comment by tsigo** [comment]
Any reason this couldn't/shouldn't be expanded to include local branches as well?

**Comment by tabfugnic** [comment]
@iwz Little late to the game, but it does work beautifully on debian

**Pull request merged**
