### PR TITLE
Explicity state to clone repo in home directory

### PR DESCRIPTION
**Pull request by brittballard**

### CODE REVIEW

**Comment by gylaz** [comment]
How about instead of cloning into `HOME`, we document how to edit the paths in [`rcrc`](https://github.com/thoughtbot/dotfiles/blob/master/rcrc)? That's what I usually do, and I think so does @croaky.

**Comment by brittballard** [comment]
@gylaz I'm good with that. I'll modify and re-push tomorrow.

**Comment by croaky** [comment]
Yeah

https://github.com/thoughtbot/dotfiles/blob/master/rcrc

https://github.com/croaky/dotfiles/blob/master/rcrc

**Comment by gylaz** [comment]
@brittballard Did you get a chance to re-visit this?

**Comment by gylaz** [comment]
I've opened this PR to provide an example: https://github.com/thoughtbot/dotfiles/pull/404

Let me know what you think.

**Comment by sheck** [comment]
+1

Wish I would have had this when I started using dotfiles — it was a little confusing. I ended up [symlinking my repo to ~/dotfiles/ to get it to work.](https://github.com/sheck/dotfiles/commit/96d8f9abb8da6a4d904f7e63a202ceae72682a7d)

**Comment by geoffharcourt** [comment]
Closing this in favor of #404, which will provide clarification.

**Pull request closed without merging**
