### PR TITLE
Link to version in Spanish

### PR DESCRIPTION
**Pull request by HoracioChavez**
- Adds a `Translations` section.
- Adds a link to[ Spanish version](https://github.com/CodigoSemilla/dotfiles/blob/master/README.md).

### CODE REVIEW

**Comment by geoffharcourt** [comment]
Hi! This is great! 

Rather than linking to another repository (that appears to be a fork with the translated README), could we consider having README-ES.md in this repo and keeping everything in one place?

**Comment by HoracioChavez** [comment]
Hi ! Everything in one place sounds even better to me! I'll switch to `README-ES.md`. 

I made another PR for laptop: https://github.com/thoughtbot/laptop/pull/512. I'll change that to `README-ES.md` too.  Also, I'll translate `paperclip`, `factory_girl`, and `shoulda-matchers`. 

✌️

**Comment by geoffharcourt** [comment]
@HoracioChavez this is amazing! I am looking forward to announcing these changes in our OSS newsletter.

**Comment by HoracioChavez** [comment]
I'm closing this PR because I just made another PR (https://github.com/thoughtbot/dotfiles/pull/549) with `README-ES.md`

**Pull request closed without merging**
