### PR TITLE
Replace CtrlP with FZF

### PR DESCRIPTION
**Pull request by rickpeyton**
This is probably a long shot, but I thought I'd throw it out there and get feedback. If you all pick it up then I won't have to carry a fork 👍

### CODE REVIEW

**Comment by geoffharcourt** [comment]
I do this myself, but I've been reluctant to force an extra dependency installation on users. Let's think this over before we make a decision.

**Comment by christoomey** [comment]
I'm also using fzf.vim in place of CtrlP, but similar to Geoff I think this may be a bit much to change in the dotfiles as there are some features that fzf does not support, and some non trivial differences in the interface. Specific features I can think of are fzf not filtering out the current buffer from the file list, and fzf not remembering the previous entry.

**Comment by rickpeyton** [comment]
For anyone that happens upon this PR and wants to give FZF a try... I like the way you guys managed it.

https://github.com/geoffharcourt/dotfiles-local/blob/master/vimrc.bundles.local#L28
https://github.com/geoffharcourt/dotfiles-local/blob/373b3301a48a3417e3e2be9bf611936d1056b51c/vim/plugin/mappings.vim#L48

https://github.com/christoomey/dotfiles/blob/master/vim/rcplugins/fzf#L25-L31

**Comment by geoffharcourt** [comment]
I'm reluctant to force another dependency on users, so I'm going to close this out. FZF will continue on in our local dotfile customizations...

**Pull request closed without merging**
