### PR TITLE
Remove unused Easter egg

### PR DESCRIPTION
**Pull request by mike-burns**
The `ranch` subcommand is annoying to skip and adds clutter to our
system, which only encourages people not to use our dotfiles as a base.
Remove it to get customizability back.

### CODE REVIEW

**Comment by blainesch** [comment]
Related: #412

**Comment by teoljungberg** [comment]
I can get behind this.

**Comment by MattMSumner** [comment]
screen shot 2015-10-09 at 11 16 52 am

screen shot 2015-10-09 at 11 17 25 am

@mike-burns you are quick!

**Comment by geoffharcourt** [comment]
Goodbye, sweet beans, you will never be forgotten.

**Pull request merged**
