### PR TITLE
Isolate ALE settings into its own augroup

### PR DESCRIPTION
**Pull request by ashwinvidiyala**
For Issue #607: How To Deactivate Ale?

### CODE REVIEW

**Comment by christoomey** [comment]
@ashwinvidiyala I did a small bit of testing locally (I've actually not used this feature before) and it looks like there might be some edge cases and/or warnings. I think you can handle them by adding `silent! augroup! ale` to your Vimrc, but can you please test that works without any issues and achieves the desired outcome?

**Comment by ashwinvidiyala** [comment]
@christoomey I've tried using `silent! augroup! ale` and also this:
```
augroup ale
  autocmd!
augroup END
```

Neither work

**Comment by ashwinvidiyala** [comment]
Hey
Just wanted to see what was happening with this.

**Comment by ashwinvidiyala** [comment]
@christoomey Is this going to be merged, or should I just go ahead and close the PR?

**Comment by geoffharcourt** [comment]
Hi @ashwinvidiyala I resolved some merge conflicts and merged your changes as 695d92f. Thanks for figuring this out and for your contribution!

**Pull request closed without merging**
