### PR TITLE
Add `gca` alias

### PR DESCRIPTION
**Pull request by jessieay**
* I type this one zillion times per day
* It is annoying

### CODE REVIEW

**Comment by croaky** [comment]
g ca may already exist in here! One extra character, though :(

**Comment by jessieay** [comment]
yes! just saw that after reading https://github.com/thoughtbot/dotfiles/pull/482 

wil close :)

very excited to use `g ca` despite the torturous extra char

**Comment by JoelQ** [comment]
FWIW, I run almost all my git commands in git shell (https://github.com/thoughtbot/gitsh) so I only need to type `ca` (2 chars!).

**Comment by christoomey** [comment]
I'll second gitsh (it's amazing!), specifically [accessed via an on-demand tmux pane](https://thoughtbot.com/upcase/videos/gitsh#tmux-binding).

**Comment by geoffharcourt** [comment]
I saw this in action in @christoomey's terminal and I think it may have finally sold me on gitsh.

**Pull request closed without merging**
