### PR TITLE
Add the `-v` flag to `commit --amend`.

### PR DESCRIPTION
**Pull request by blainesch**
This allows us to always see things we are going to commit, even if we
are amending.

### CODE REVIEW

**Comment by jferris** [comment]
Seems good to me.

**Comment by blainesch** [comment]
Re-pushed. I didn't change code, just who I committed as, it didn't have my correct email.

What's the correct way to version the .local files?

**Comment by blainesch** [comment]
Rebased.

**Comment by iwz** [comment]
:+1:

**Comment by gylaz** [comment]
Thanks @blainesch!

**Comment by croaky** [comment]
Oh good call.

**Pull request merged**
