### PR TITLE
Add a command to fixup your commit.

### PR DESCRIPTION
**Pull request by blainesch**
I was originally thinking `git fixup` would be good here, but I see there's two letter standard going on.

### CODE REVIEW

**Comment by mike-burns** [comment]
Is this something we do often? Is this something I should be doing more often?

**Comment by calleerlandsson** [comment]
I use it whenever I add a commit to a branch with the intention of squashing it into another before merging the branch. `commit --fixup SHA` is made to work with with `rebase --interactive --autosquash`.

**Comment by geoffharcourt** [comment]
I started doing this after reading @georgebrock's [excellent blog post](https://robots.thoughtbot.com/autosquashing-git-commits) on autosquashing. It's particularly nice when you want to temporarily submit a commit (that will later be squashed or fixed up) to suggest a resolution to a PR reviewer's comments without rebasing and changing commit references while a review might still be in progress.

**Comment by jsteiner** [comment]
If everyone likes this, it might be nice to have `sq = commit --squash` in there as well.

**Comment by mike-burns** [comment]
Is this something we do so often that the short `fu` and `sq` aliases make more sense than `fixup` and `squash` ?

**Comment by blainesch** [comment]
The [autosquash flag which is on](https://github.com/thoughtbot/dotfiles/blob/master/gitconfig#L25) already inside of the global `gitconfig`.

**Comment by blainesch** [comment]
I have updated to include both `squash` and `fixup` as commands.

**Comment by gylaz** [comment]
I'd like to push back on this. In a normal workflow process we don't type this enough to save us a few characters. I think our dotfiles should be slim enough to be accessible to new-comers, rather than bulk up with all of the possible commands we *might* use during the day. My $0.02.

**Comment by blainesch** [comment]
Amend actually already exists as `git ca` I realized as I was typing it.

There was a level of indirection, since it lives in bin though.

https://github.com/thoughtbot/dotfiles/blob/master/bin/git-ca

**Comment by blainesch** [comment]
I've updated the commit to just have `fixup`.

**Comment by geoffharcourt** [comment]
Hi @blainesch I think there's enough disagreement on this that I'm going to close without merging. (However I'll probably be pulling this into my own overrides.) Thanks for your contribution(s) to dotfiles.

**Pull request closed without merging**
