### PR TITLE
Add git delete-branch completion

### PR DESCRIPTION
**Pull request by keith**
Closes https://github.com/thoughtbot/dotfiles/issues/355 via https://coderwall.com/p/wjuoag/creating-custom-git-commands-autocompletion

### CODE REVIEW

**Comment by gylaz** [comment]
:+1: Nice!

**Comment by croaky** [comment]
Thanks for taking a stab, @Keithbsmiley. I checked out this branch, ran `rcup -d dotfiles`, opened a new shell, and ran:

```
maitre-d master % g branch
  dc-collect-location
  dc-fix-svg-article
* master
maitre-d master % g delete-branch dc-<Tab>
```

I wasn't getting autocompletion, though. I also tried it with `git` instead of the `g` alias.

I'm using thoughtbot/dotfiles and https://github.com/croaky/dotfiles.

**Comment by Keithbsmiley** [comment]
This definitely doesn't seem to work with @croaky's configuration. If some other people could test it to make sure it's not just him that would be awesome!

**Comment by croaky** [comment]
Some other things I tried with no luck:

* Upgraded Git through Homebrew
* Installed Zsh through Homebrew
* Renamed `_git_delete_branch` to `_git_delete-branch`
* Renamed `_git_delete_branch` to `_git-delete-branch`

**Comment by gylaz** [comment]
Just tried it, not luck, either. Guessing I've got the same setup as @croaky.

**Comment by aaronmcadam** [comment]
I just got this working by re-ordering the loading of the completions: https://github.com/aaronmcadam/dotfiles/commit/0531b63e7f214ac236db816a152eded1f9c6a5cc

**Comment by croaky** [comment]
@aaronmcadam Nice! I'm getting jealous now... :)

Trying to figure out what's different on @gylaz's and my setup compared to yours and @Keithbsmiley's...

My setup (Yosemite):

```
% echo $fpath
/Users/croaky/.zsh/completion /usr/share/zsh/site-functions /usr/share/zsh/5.0.5/functions
% git --version
git version 2.3.5
 % zsh --version
zsh 5.0.7 (x86_64-apple-darwin14.0.0)
% echo $PATH
.git/safe/../../bin:/Users/croaky/.rbenv/shims:/Users/croaky/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/croaky/go/bin:/usr/local/Cellar/go/1.4.2/libexec/bin
```

**Comment by aaronmcadam** [comment]
hey @croaky, one thing to note is that although my dotfiles are heavily influenced by thoughtbot's, they are not a fork and designed by me. I tried to find what I was doing differently when I finally worked it out and it was the re-ordering of the `compinit` that fixed it in the end. Unfortunately, the docs and blog posts around zsh completions are hazy at best so I don't know enough to explain how I got mine working.

**Comment by gylaz** [comment]
Closing this, since it doesn't seem to solve the problem. Thanks for the help @keith!

**Pull request closed without merging**
