### PR TITLE
Update copyright date

### PR DESCRIPTION
**Pull request by geoffharcourt**
It's 2016.

### CODE REVIEW

**Comment by blainesch** [comment]
The [LICENSE](https://github.com/thoughtbot/dotfiles/blob/master/LICENSE#L5) file has a date too.

**Comment by geoffharcourt** [comment]
Which was even more out of date! Thanks for the spot @blainesch!

**Comment by bernerdschaefer** [comment]
IANAL, but based on http://www.copyright.gov/circs/circ03.pdf and http://www.copyright.gov/circs/circ01.pdf, it seems that only the original date of publication is needed (if even that).

What about making it "Copyright (c) 2009 thoughtbot", so the dates can't fall behind?

**Comment by geoffharcourt** [comment]
@bernerdschaefer I was hoping there was a good cause to remove it entirely, but this works too. My only concern is that having a date but having it be quite a while in the past may make the project look unmaintained at a quick glance. Am I being paranoid?

**Comment by bernerdschaefer** [comment]
@geoffharcourt What about merging this as-is, and then starting a discussion on thoughtbot/guides so we can tackle this for multiple projects?

**Comment by geoffharcourt** [comment]
:+1: Thanks @bernerdschaefer and @blainesch for the review and :eyes:

**Pull request merged**
